### ISSUE TITLE
@synonymdev/slashtags-docid not found in NPM registry

### ISSUE THREAD

**Issue by Entryist** [synonymdev/slashtags#16]
Root-level `npm run install` fails with:

```
npm ERR! code E404
npm ERR! 404 Not Found - GET https://registry.npmjs.org/@synonymdev%2fslashtags-docid - Not found
npm ERR! 404 
npm ERR! 404  '@synonymdev/slashtags-docid@^0.1.0' is not in this registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
```

The `url` package depends on `@synonymdev/slashtags-docid` which is [not found in NPM](https://www.npmjs.com/search?q=synonymdev).

The wallet demo in `demo/auth/wallet` similarly fails on `npm install`, as its dependency `@synonymdev/slashtags-url` expects `@synonymdev/slashtags-docid`.

**Comment by Entryist** [comment]
`npm run install` works now that `slashtags-docid` has been [published](https://www.npmjs.com/package/@synonymdev/slashtags-docid), but the root-level `package-lock.json` is looking for a local `packages/docid` folder that doesn't exist.

```
"@synonymdev/slashtags-docid": {
  "version": "file:packages/docid",
  "requires": {
    "@synonymdev/slashtags-common": "^0.1.0",
    "multiformats": "^9.4.6"
  }
},
```

Root-level node_modules looks like:

![symlink1](https://user-images.githubusercontent.com/14167547/142491333-e3f49fee-f324-4e15-a263-c584bc888cb0.png)

Probably need to delete and regenerate package-lock.json so it pulls `docid` from npm?

**Comment by Nazeh** [comment]
Thanks, @Entryist for the report and sorry for all that confusion, fwiw, `docid` is indeed deprecated, and I am working on updating `slashtags-url` to remove `docid` as a dependency, but currently the demo for `slashtags-accounts` doesn't depend on `slashtags-url` either, but it will after updating it, and refactoring some of the logic out of `slashtags-actions` and `slashtags-accounts` to be in `slashtags-url`.

**Comment by xraid** [comment]
please consider change ```slashtags-url``` to ```slashtags-uri``` for a more flexible  naming in regards to any future protocol adoptions ...
