### ISSUE TITLE
Demos link is a deadend link

### ISSUE THREAD

**Issue by gked** [synonymdev/slashtags#20]
Can you fix the dead link from this sentence in the readme.md [file](https://github.com/synonymdev/slashtags)?

**Currently the best way to get familiar with the existing features is to check the [Demos](https://github.com/synonymdev/slashtags/blob/master/demo/README.md).**

I get the image below when I click on "demos" link.
![image](https://user-images.githubusercontent.com/12704474/142750187-3f437611-e77a-47db-b9a2-446d442f0763.png)

**Comment by Nazeh** [comment]
@gked Thanks for pointing that out, fixed now.
